spring.application.name=Bank-backend

spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true



server.port=8081
spring.datasource.url=jdbc:postgresql://localhost/bank_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update